FROM node:16-alpine AS build
WORKDIR /frontend
RUN npm install -g angular/cli
COPY package.json .1
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/dist/nameProject.directory /usr/share/nginx/html
EXPOSE 9090
